services:
  - type: web
    name: wa-delegation-api
    runtime: docker
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    plan: free
    envVars:
      - key: DB_HOST
        value: 87.106.200.69
      - key: DB_PORT
        value: 3306
      - key: DB_USER
        value: emarket_bot
      - key: DB_PASSWORD
        value: 1234567
      - key: DB_NAME
        value: emarketing_bot
      - key: WA_PRODUCT_ID
        value: 2ddecd7e-d130-48b7-9c69-2b5a6f095060
      - key: WA_TOKEN
        value: 5afba9c9-7ca5-47b5-8ed4-65b98950f088
      - key: WA_PHONE_ID
        value: 94509
      - key: WA_BASE_URL
        value: https://gate.whapi.cloud
      - key: OPENAI_API_KEY
        sync: false        # you'll paste this manually in Render dashboard
      - key: GOOGLE_DRIVE_FOLDER_ID
        sync: false        # paste manually
      - key: GOOGLE_SERVICE_ACCOUNT_JSON
        value: /etc/secrets/google_service_account.json
      - key: FRONTEND_URL
        value: "*"
